### ISSUE TITLE
error by install windows 11 pro on raspberry pi 5

### ISSUE THREAD

**Issue by mehrak20** [Botspot/wor-flasher#153]
## Setup:

- Which version of Windows you chose  Win 11 Pro 
- Raspberry Pi model 5
- Name of SD card you tried to flash (some are too slow or too small) amazon basics 128GB  micro sd 
- What day you first downloaded wor-flasher today 
- What linux operating system you are using to run wor-flasher on. Raspberry Pi OS
## Procedure:
Tell us what you did, step by step. Be specific enough so that one of us would be able to replicate your setup.

I flashed my SD using Wor Flasher.
reboot and get into Windows Setup, select my SSD and it always goes into error. I added the log.

[WoR-PE.log](https://github.com/Botspot/wor-flasher/files/15052882/WoR-PE.log)

_2024-03-16 03:48:37.1240 [info] WoR-PE (version 1.1.0.0)
2024-03-16 03:48:37.1886 [info] Copyright © 2018-2022 Mario Bălănică. All Rights Reserved.
2024-03-16 03:48:37.1975 [info] OS: Windows (TM) 10 Preinstallation Environment ver 2009 (22621.2506.arm64fre.ni_release_svc_prod3.231018-1809)
2024-03-16 03:48:37.1975 [info] System model: Raspberry Pi 5 Model B
2024-03-16 03:48:37.1975 [info] Device display short name: Raspberry Pi 5 Model B
2024-03-16 03:48:37.2309 [debug] Loaded configuration file:
2024-03-16 03:48:37.2309 [debug]   PreferredImageEditionId: Professional
2024-03-16 03:48:37.2593 [info] Loading driver list...
2024-03-16 03:48:37.2593 [info] Drivers loaded successfully!
2024-03-16 03:48:41.3596 [info] Loading disks...
2024-03-16 03:48:42.0132 [info] Disk 1 - Generic USD00 SD Card - Removable Media - 117 GB
2024-03-16 03:48:42.0132 [info] Disk 0 - KIOXIA-EXCERIA G2 SSD - Fixed hard disk media - 931 GB
2024-03-16 03:48:42.0132 [info] 2 disk(s) found
2024-03-16 03:48:42.0132 [info] Finding PE disk...
2024-03-16 03:48:42.0298 [info] Mounting partitions on disk 1...
2024-03-16 03:48:42.0474 [debug] Creating diskpart script with the following commands: select disk 1 , select partition 1 , assign letter=A , exit
2024-03-16 03:48:42.0555 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:48:43.5913 [debug] diskpart.exe process output:
2024-03-16 03:48:43.5913 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 1 ist jetzt der gew„hlte Datentr„ger.

Partition 1 ist jetzt die gew„hlte Partition.

Der Laufwerkbuchstabe oder der Bereitstellungspunkt wurde zugewiesen.

Datentr„gerpartitionierung wird beendet...

2024-03-16 03:48:43.5913 [debug] Exit code: 0
2024-03-16 03:48:43.6031 [debug] Creating diskpart script with the following commands: select disk 1 , select partition 2 , assign letter=B , exit
2024-03-16 03:48:43.6175 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:48:44.7972 [debug] diskpart.exe process output:
2024-03-16 03:48:44.7972 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 1 ist jetzt der gew„hlte Datentr„ger.

Partition 2 ist jetzt die gew„hlte Partition.

Der Laufwerkbuchstabe oder der Bereitstellungspunkt wurde zugewiesen.

Datentr„gerpartitionierung wird beendet...

2024-03-16 03:48:44.7972 [debug] Exit code: 0
2024-03-16 03:48:44.8054 [info] Partitions successfully mounted!
2024-03-16 03:48:44.8054 [info]   Boot: A
2024-03-16 03:48:44.8054 [info]   Win: B
2024-03-16 03:48:44.8054 [info] Found PE disk at index 1
2024-03-16 03:48:48.9529 [info] Selected disk: Disk 0 - KIOXIA-EXCERIA G2 SSD - Fixed hard disk media - 931 GB
2024-03-16 03:48:50.1908 [info] Finding image file...
2024-03-16 03:48:50.2013 [info] Found image file at: B:\install.wim
2024-03-16 03:48:50.2013 [info] Getting image editions...
2024-03-16 03:48:50.3194 [info] Edition 1: Windows 11 Home (Core) build 22621.2861 arch ARM64
2024-03-16 03:48:50.3231 [info] Edition 2: Windows 11 Pro (Professional) build 22621.2861 arch ARM64
2024-03-16 03:48:50.3231 [info] Selected edition: Windows 11 Pro build 22621.2861
2024-03-16 03:48:54.7558 [info] -- Installation details --
2024-03-16 03:48:54.7558 [info] PeInstallDisk
2024-03-16 03:48:54.7558 [info]   Index: 1
2024-03-16 03:48:54.7558 [info]   Name: Generic USD00 SD Card
2024-03-16 03:48:54.7558 [info]   Type: Removable Media
2024-03-16 03:48:54.7558 [info]   Size: 117
2024-03-16 03:48:54.7558 [info] DestinationDisk
2024-03-16 03:48:54.7558 [info]   Index: 0
2024-03-16 03:48:54.7672 [info]   Name: KIOXIA-EXCERIA G2 SSD
2024-03-16 03:48:54.7672 [info]   Type: Fixed hard disk media
2024-03-16 03:48:54.7672 [info]   Size: 931
2024-03-16 03:48:54.7672 [info] Image
2024-03-16 03:48:54.7672 [info]   Path: B:\install.wim
2024-03-16 03:48:54.7672 [info]   Index: 2
2024-03-16 03:48:54.7672 [info]   Name: Windows 11 Pro
2024-03-16 03:48:54.7672 [info]   Arch: ARM64
2024-03-16 03:48:54.7672 [info]   Build: 22621.2861
2024-03-16 03:48:54.7672 [info] -- End of installation details --
2024-03-16 03:48:54.7672 [info] The installation process has started!
2024-03-16 03:48:54.7964 [info] Formatting the target device...
2024-03-16 03:48:54.7996 [debug] Creating diskpart script with the following commands: select disk 0 , clean , exit
2024-03-16 03:48:54.7996 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:48:55.9488 [debug] diskpart.exe process output:
2024-03-16 03:48:55.9488 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Der Datentr„ger wurde bereinigt.

Datentr„gerpartitionierung wird beendet...

2024-03-16 03:48:55.9488 [debug] Exit code: 0
2024-03-16 03:48:59.4678 [info] The target device has been erased!
2024-03-16 03:48:59.4678 [debug] Creating diskpart script with the following commands: select disk 0 , convert mbr , convert gpt , list partition , exit
2024-03-16 03:48:59.4678 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:49:50.6500 [debug] diskpart.exe process output:
2024-03-16 03:49:50.6500 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Fehler in DiskPart: Unzul„ssige Funktion.
Weitere Informationen finden Sie im Systemereignisprotokoll.

2024-03-16 03:49:50.6500 [warn] Exit code: -2147024895
2024-03-16 03:49:50.6716 [warn] Task retry attempt 1/4 failed!
2024-03-16 03:49:50.6782 [warn] Retrying... (3.5s delay)
2024-03-16 03:49:54.1905 [info] Formatting the target device...
2024-03-16 03:49:54.1905 [debug] Creating diskpart script with the following commands: select disk 0 , clean , exit
2024-03-16 03:49:54.1905 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:49:54.2793 [debug] diskpart.exe process output:
2024-03-16 03:49:54.2793 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Der Datentr„ger wurde bereinigt.

Datentr„gerpartitionierung wird beendet...

2024-03-16 03:49:54.2793 [debug] Exit code: 0
2024-03-16 03:49:57.8129 [info] The target device has been erased!
2024-03-16 03:49:57.8129 [debug] Creating diskpart script with the following commands: select disk 0 , convert mbr , convert gpt , list partition , exit
2024-03-16 03:49:57.8129 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:49:57.8883 [debug] diskpart.exe process output:
2024-03-16 03:49:57.8883 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Fehler in DiskPart: Unzul„ssige Funktion.
Weitere Informationen finden Sie im Systemereignisprotokoll.

2024-03-16 03:49:57.8883 [warn] Exit code: -2147024895
2024-03-16 03:49:57.9083 [warn] Task retry attempt 2/4 failed!
2024-03-16 03:49:57.9083 [warn] Retrying... (3.5s delay)
2024-03-16 03:50:01.4204 [info] Formatting the target device...
2024-03-16 03:50:01.4204 [debug] Creating diskpart script with the following commands: select disk 0 , clean , exit
2024-03-16 03:50:01.4204 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:50:01.4968 [debug] diskpart.exe process output:
2024-03-16 03:50:01.4968 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Der Datentr„ger wurde bereinigt.

Datentr„gerpartitionierung wird beendet...

2024-03-16 03:50:01.4968 [debug] Exit code: 0
2024-03-16 03:50:05.0156 [info] The target device has been erased!
2024-03-16 03:50:05.0156 [debug] Creating diskpart script with the following commands: select disk 0 , convert mbr , convert gpt , list partition , exit
2024-03-16 03:50:05.0156 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:51:21.2424 [debug] diskpart.exe process output:
2024-03-16 03:51:21.2424 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Fehler in DiskPart: Die Anforderung konnte wegen eines E/A-Ger„tefehlers nicht ausgefhrt werden.
Weitere Informationen finden Sie im Systemereignisprotokoll.

2024-03-16 03:51:21.2424 [warn] Exit code: -2147023779
2024-03-16 03:51:21.2772 [warn] Task retry attempt 3/4 failed!
2024-03-16 03:51:21.2772 [warn] Retrying... (3.5s delay)
2024-03-16 03:51:24.7891 [info] Formatting the target device...
2024-03-16 03:51:24.7891 [debug] Creating diskpart script with the following commands: select disk 0 , clean , exit
2024-03-16 03:51:24.7891 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:51:24.8788 [debug] diskpart.exe process output:
2024-03-16 03:51:24.8788 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Der Datentr„ger wurde bereinigt.

Datentr„gerpartitionierung wird beendet...

2024-03-16 03:51:24.8788 [debug] Exit code: 0
2024-03-16 03:51:28.4056 [info] The target device has been erased!
2024-03-16 03:51:28.4056 [debug] Creating diskpart script with the following commands: select disk 0 , convert mbr , convert gpt , list partition , exit
2024-03-16 03:51:28.4056 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:51:28.4814 [debug] diskpart.exe process output:
2024-03-16 03:51:28.4814 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Fehler in DiskPart: Unzul„ssige Funktion.
Weitere Informationen finden Sie im Systemereignisprotokoll.

2024-03-16 03:51:28.4814 [warn] Exit code: -2147024895
2024-03-16 03:51:28.5027 [warn] Task retry attempt 4/4 failed!
2024-03-16 03:51:28.5171 [error] Aborting...
2024-03-16 03:51:28.5171 [error] WoR_PE.Exceptions.ProcessException: The diskpart.exe process has returned an error!
   at WoR_PE.Setup.SetupProcess.RunProcessTaskWithRetry(Func`1 task)
   at WoR_PE.Setup.SetupProcess.PrepareDestinationDisk()
   at WoR_PE.Setup.SetupProcess.DeploymentTask()
   at WoR_PE.Setup.SetupProcess.Run(IWin32Window parent)
2024-03-16 03:51:28.5783 [warn] The installation could not be finished!
2024-03-16 03:51:49.6439 [info] Elapsed time: 00:02:54
2024-03-16 03:53:26.2919 [info] -- Installation details --
2024-03-16 03:53:26.2919 [info] PeInstallDisk
2024-03-16 03:53:26.3077 [info]   Index: 1
2024-03-16 03:53:26.3077 [info]   Name: Generic USD00 SD Card
2024-03-16 03:53:26.3077 [info]   Type: Removable Media
2024-03-16 03:53:26.3077 [info]   Size: 117
2024-03-16 03:53:26.3077 [info] DestinationDisk
2024-03-16 03:53:26.3225 [info]   Index: 0
2024-03-16 03:53:26.3225 [info]   Name: KIOXIA-EXCERIA G2 SSD
2024-03-16 03:53:26.3225 [info]   Type: Fixed hard disk media
2024-03-16 03:53:26.3225 [info]   Size: 931
2024-03-16 03:53:26.3225 [info] Image
2024-03-16 03:53:26.3378 [info]   Path: B:\install.wim
2024-03-16 03:53:26.3378 [info]   Index: 2
2024-03-16 03:53:26.3378 [info]   Name: Windows 11 Pro
2024-03-16 03:53:26.3378 [info]   Arch: ARM64
2024-03-16 03:53:26.3546 [info]   Build: 22621.2861
2024-03-16 03:53:26.3546 [info] -- End of installation details --
2024-03-16 03:53:26.3546 [info] The installation process has started!
2024-03-16 03:53:26.3546 [info] Formatting the target device...
2024-03-16 03:53:26.3546 [debug] Creating diskpart script with the following commands: select disk 0 , clean , exit
2024-03-16 03:53:26.3726 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:53:26.4495 [debug] diskpart.exe process output:
2024-03-16 03:53:26.4495 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Der Datentr„ger wurde bereinigt.

Datentr„gerpartitionierung wird beendet...

2024-03-16 03:53:26.4495 [debug] Exit code: 0
2024-03-16 03:53:29.9725 [info] The target device has been erased!
2024-03-16 03:53:29.9725 [debug] Creating diskpart script with the following commands: select disk 0 , convert mbr , convert gpt , list partition , exit
2024-03-16 03:53:29.9725 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:53:50.6797 [debug] diskpart.exe process output:
2024-03-16 03:53:50.6797 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Fehler in DiskPart: Unzul„ssige Funktion.
Weitere Informationen finden Sie im Systemereignisprotokoll.

2024-03-16 03:53:50.6797 [warn] Exit code: -2147024895
2024-03-16 03:53:50.6797 [warn] Task retry attempt 1/4 failed!
2024-03-16 03:53:50.6945 [warn] Retrying... (3.5s delay)
2024-03-16 03:53:54.1979 [info] Formatting the target device...
2024-03-16 03:53:54.1979 [debug] Creating diskpart script with the following commands: select disk 0 , clean , exit
2024-03-16 03:53:54.2151 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:53:54.2914 [debug] diskpart.exe process output:
2024-03-16 03:53:54.2914 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Der Datentr„ger wurde bereinigt.

Datentr„gerpartitionierung wird beendet...

2024-03-16 03:53:54.2914 [debug] Exit code: 0
2024-03-16 03:53:57.8026 [info] The target device has been erased!
2024-03-16 03:53:57.8026 [debug] Creating diskpart script with the following commands: select disk 0 , convert mbr , convert gpt , list partition , exit
2024-03-16 03:53:57.8203 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:54:48.0131 [debug] diskpart.exe process output:
2024-03-16 03:54:48.0131 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Fehler in DiskPart: Die Anforderung konnte wegen eines E/A-Ger„tefehlers nicht ausgefhrt werden.
Weitere Informationen finden Sie im Systemereignisprotokoll.

2024-03-16 03:54:48.0131 [warn] Exit code: -2147023779
2024-03-16 03:54:48.0131 [warn] Task retry attempt 2/4 failed!
2024-03-16 03:54:48.0440 [warn] Retrying... (3.5s delay)
2024-03-16 03:54:51.5619 [info] Formatting the target device...
2024-03-16 03:54:51.5619 [debug] Creating diskpart script with the following commands: select disk 0 , clean , exit
2024-03-16 03:54:51.5619 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:54:51.6469 [debug] diskpart.exe process output:
2024-03-16 03:54:51.6469 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Der Datentr„ger wurde bereinigt.

Datentr„gerpartitionierung wird beendet...

2024-03-16 03:54:51.6469 [debug] Exit code: 0
2024-03-16 03:54:55.1693 [info] The target device has been erased!
2024-03-16 03:54:55.1693 [debug] Creating diskpart script with the following commands: select disk 0 , convert mbr , convert gpt , list partition , exit
2024-03-16 03:54:55.1693 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:54:55.2404 [debug] diskpart.exe process output:
2024-03-16 03:54:55.2404 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Fehler in DiskPart: Unzul„ssige Funktion.
Weitere Informationen finden Sie im Systemereignisprotokoll.

2024-03-16 03:54:55.2404 [warn] Exit code: -2147024895
2024-03-16 03:54:55.2560 [warn] Task retry attempt 3/4 failed!
2024-03-16 03:54:55.2560 [warn] Retrying... (3.5s delay)
2024-03-16 03:54:58.7666 [info] Formatting the target device...
2024-03-16 03:54:58.7835 [debug] Creating diskpart script with the following commands: select disk 0 , clean , exit
2024-03-16 03:54:58.7835 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:54:58.8495 [debug] diskpart.exe process output:
2024-03-16 03:54:58.8495 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Der Datentr„ger wurde bereinigt.

Datentr„gerpartitionierung wird beendet...

2024-03-16 03:54:58.8495 [debug] Exit code: 0
2024-03-16 03:55:02.3614 [info] The target device has been erased!
2024-03-16 03:55:02.3614 [debug] Creating diskpart script with the following commands: select disk 0 , convert mbr , convert gpt , list partition , exit
2024-03-16 03:55:02.3789 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:55:52.5514 [debug] diskpart.exe process output:
2024-03-16 03:55:52.5514 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Fehler in DiskPart: Unzul„ssige Funktion.
Weitere Informationen finden Sie im Systemereignisprotokoll.

2024-03-16 03:55:52.5514 [warn] Exit code: -2147024895
2024-03-16 03:55:52.5514 [warn] Task retry attempt 4/4 failed!
2024-03-16 03:55:52.5811 [error] Aborting...
2024-03-16 03:55:52.5811 [error] WoR_PE.Exceptions.ProcessException: The diskpart.exe process has returned an error!
   at WoR_PE.Setup.SetupProcess.RunProcessTaskWithRetry(Func`1 task)
   at WoR_PE.Setup.SetupProcess.PrepareDestinationDisk()
   at WoR_PE.Setup.SetupProcess.DeploymentTask()
   at WoR_PE.Setup.SetupProcess.Run(IWin32Window parent)
2024-03-16 03:55:52.5811 [warn] The installation could not be finished!
2024-03-16 03:55:54.7153 [info] Elapsed time: 00:02:28
2024-03-16 03:55:59.7390 [info] -- Installation details --
2024-03-16 03:55:59.7390 [info] PeInstallDisk
2024-03-16 03:55:59.7390 [info]   Index: 1
2024-03-16 03:55:59.7390 [info]   Name: Generic USD00 SD Card
2024-03-16 03:55:59.7390 [info]   Type: Removable Media
2024-03-16 03:55:59.7571 [info]   Size: 117
2024-03-16 03:55:59.7701 [info] DestinationDisk
2024-03-16 03:55:59.7701 [info]   Index: 0
2024-03-16 03:55:59.7701 [info]   Name: KIOXIA-EXCERIA G2 SSD
2024-03-16 03:55:59.7701 [info]   Type: Fixed hard disk media
2024-03-16 03:55:59.7701 [info]   Size: 931
2024-03-16 03:55:59.8014 [info] Image
2024-03-16 03:55:59.8014 [info]   Path: B:\install.wim
2024-03-16 03:55:59.8014 [info]   Index: 2
2024-03-16 03:55:59.8014 [info]   Name: Windows 11 Pro
2024-03-16 03:55:59.8014 [info]   Arch: ARM64
2024-03-16 03:55:59.8327 [info]   Build: 22621.2861
2024-03-16 03:55:59.8327 [info] -- End of installation details --
2024-03-16 03:55:59.8327 [info] The installation process has started!
2024-03-16 03:55:59.8327 [info] Formatting the target device...
2024-03-16 03:55:59.8484 [debug] Creating diskpart script with the following commands: select disk 0 , clean , exit
2024-03-16 03:55:59.8658 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:55:59.9412 [debug] diskpart.exe process output:
2024-03-16 03:55:59.9413 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Der Datentr„ger wurde bereinigt.

Datentr„gerpartitionierung wird beendet...

2024-03-16 03:55:59.9413 [debug] Exit code: 0
2024-03-16 03:56:03.4586 [info] The target device has been erased!
2024-03-16 03:56:03.4586 [debug] Creating diskpart script with the following commands: select disk 0 , convert mbr , convert gpt , list partition , exit
2024-03-16 03:56:03.4586 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:56:53.5888 [debug] diskpart.exe process output:
2024-03-16 03:56:53.5888 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Fehler in DiskPart: Unzul„ssige Funktion.
Weitere Informationen finden Sie im Systemereignisprotokoll.

2024-03-16 03:56:53.5888 [warn] Exit code: -2147024895
2024-03-16 03:56:53.6106 [warn] Task retry attempt 1/4 failed!
2024-03-16 03:56:53.6106 [warn] Retrying... (3.5s delay)
2024-03-16 03:56:57.1281 [info] Formatting the target device...
2024-03-16 03:56:57.1447 [debug] Creating diskpart script with the following commands: select disk 0 , clean , exit
2024-03-16 03:56:57.1447 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:56:57.2262 [debug] diskpart.exe process output:
2024-03-16 03:56:57.2262 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Der Datentr„ger wurde bereinigt.

Datentr„gerpartitionierung wird beendet...

2024-03-16 03:56:57.2262 [debug] Exit code: 0
2024-03-16 03:57:00.7453 [info] The target device has been erased!
2024-03-16 03:57:00.7453 [debug] Creating diskpart script with the following commands: select disk 0 , convert mbr , convert gpt , list partition , exit
2024-03-16 03:57:00.7453 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:57:00.8164 [debug] diskpart.exe process output:
2024-03-16 03:57:00.8164 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Fehler in DiskPart: Unzul„ssige Funktion.
Weitere Informationen finden Sie im Systemereignisprotokoll.

2024-03-16 03:57:00.8164 [warn] Exit code: -2147024895
2024-03-16 03:57:00.8327 [warn] Task retry attempt 2/4 failed!
2024-03-16 03:57:00.8327 [warn] Retrying... (3.5s delay)
2024-03-16 03:57:04.3506 [info] Formatting the target device...
2024-03-16 03:57:04.3506 [debug] Creating diskpart script with the following commands: select disk 0 , clean , exit
2024-03-16 03:57:04.3506 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:57:04.4227 [debug] diskpart.exe process output:
2024-03-16 03:57:04.4227 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Der Datentr„ger wurde bereinigt.

Datentr„gerpartitionierung wird beendet...

2024-03-16 03:57:04.4227 [debug] Exit code: 0
2024-03-16 03:57:07.9353 [info] The target device has been erased!
2024-03-16 03:57:07.9522 [debug] Creating diskpart script with the following commands: select disk 0 , convert mbr , convert gpt , list partition , exit
2024-03-16 03:57:07.9522 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:57:58.1515 [debug] diskpart.exe process output:
2024-03-16 03:57:58.1515 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Fehler in DiskPart: Die Anforderung konnte wegen eines E/A-Ger„tefehlers nicht ausgefhrt werden.
Weitere Informationen finden Sie im Systemereignisprotokoll.

2024-03-16 03:57:58.1515 [warn] Exit code: -2147023779
2024-03-16 03:57:58.1700 [warn] Task retry attempt 3/4 failed!
2024-03-16 03:57:58.1700 [warn] Retrying... (3.5s delay)
2024-03-16 03:58:01.6909 [info] Formatting the target device...
2024-03-16 03:58:01.6909 [debug] Creating diskpart script with the following commands: select disk 0 , clean , exit
2024-03-16 03:58:01.6909 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:58:01.7775 [debug] diskpart.exe process output:
2024-03-16 03:58:01.7775 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Der Datentr„ger wurde bereinigt.

Datentr„gerpartitionierung wird beendet...

2024-03-16 03:58:01.7775 [debug] Exit code: 0
2024-03-16 03:58:05.2951 [info] The target device has been erased!
2024-03-16 03:58:05.2951 [debug] Creating diskpart script with the following commands: select disk 0 , convert mbr , convert gpt , list partition , exit
2024-03-16 03:58:05.2951 [debug] Launch diskpart.exe with the following arguments: /s "X:\diskpart.script"
2024-03-16 03:58:05.3664 [debug] diskpart.exe process output:
2024-03-16 03:58:05.3664 [debug] Standard output:

Microsoft DiskPart-Version 10.0.22621.1

Copyright (C) Microsoft Corporation.
Auf Computer: MINWINPC

Datentr„ger 0 ist jetzt der gew„hlte Datentr„ger.

Fehler in DiskPart: Unzul„ssige Funktion.
Weitere Informationen finden Sie im Systemereignisprotokoll.

2024-03-16 03:58:05.3664 [warn] Exit code: -2147024895
2024-03-16 03:58:05.3798 [warn] Task retry attempt 4/4 failed!
2024-03-16 03:58:05.3798 [error] Aborting...
2024-03-16 03:58:05.3919 [error] WoR_PE.Exceptions.ProcessException: The diskpart.exe process has returned an error!
   at WoR_PE.Setup.SetupProcess.RunProcessTaskWithRetry(Func`1 task)
   at WoR_PE.Setup.SetupProcess.PrepareDestinationDisk()
   at WoR_PE.Setup.SetupProcess.DeploymentTask()
   at WoR_PE.Setup.SetupProcess.Run(IWin32Window parent)
2024-03-16 03:58:05.3919 [warn] The installation could not be finished!
2024-03-16 04:00:50.9128 [info] Elapsed time: 00:04:51_

many thanks for your help

**Comment by Botspot** [comment]
I see you closed this issue. Did you solve the problem?
